### ISSUE TITLE
DalvikOverride: Method considered overridden by Dalvik

### ISSUE THREAD

**Issue by emakar** [JakeWharton/retrolambda#3]
Having lambdas with the same name created in both superclass and its subclass lint would report an error, e.g:
```
com.example.BaseActivity {
  protected onCreate(..) {
    doSmth(() -> {});
  }
}

com.example.details.ChildActivity {
  protected onCreate(..) {
    doSmth(() -> {});
  }
}
```
"ChildActivity: This package private method may be unintentionally overriding lambda$onCreate$0 in com.example.BaseActivity"

**Comment by JakeWharton** [comment]
Issue was migrated to the upstream project.
